include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    must_call_super: error

linter:
  rules:
    # Dart Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # Best Practices
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true

    # Null Safety
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_final_locals: true

    # Performance
    unnecessary_brace_in_string_interps: true
